function addTask() {
  const tasktext = document.getElementById("tasktext").value;

  firebase.auth().onAuthStateChanged((user) => {
    if (user) {
      var uid = user.uid;
      var email = user.email;

      // Create a new post reference with an auto-generated id
      var postListRef = firebase.database().ref("taskList");
      var newPostRef = postListRef.push();
      newPostRef.set({
        // ...
        uid: user.uid,
        email: email,
        tasktext: tasktext,
      });
      document.getElementById("tasktext").value = "";
      //   }
     

      // ...
    } else {
      // User is signed out
      // ...
    }
  });
}
 firebase
        .database()
        .ref("taskList")
        .on("value", function (snapshot) {
            var parent = document.getElementById("taskLine");
          parent.innerHTML = ""
          snapshot.forEach(function (childSnapshot) {
            var taskKey = childSnapshot.key; // Unique key generated by push()
            var taskData = childSnapshot.val(); // Object: { uid, email, tasktext }

            // console.log("Key:", taskKey);
            // console.log("Data:", taskData);
            

            var parent = document.getElementById("taskLine");
            var div = document.createElement("div");
            div.setAttribute("class", "taskcontent");
            var task = document.createElement("span");
            task.innerText = taskData.tasktext;
            var editbtn = document.createElement("button");
            editbtn.innerText = "Edit";
            var deletebtn = document.createElement("button");
            deletebtn.innerText = "Delete";
            var btns = document.createElement("div")
            btns.appendChild(editbtn);
            btns.appendChild(deletebtn);

            div.appendChild(task);
            div.appendChild(btns);
            parent.appendChild(div);
          });
        });